require_relative 'ascii_table/ascii_table'
require_relative 'ascii_table/header'
require_relative 'ascii_table/headers'
require_relative 'ascii_table/separator'
require_relative 'ascii_table/no_separator'
